services:
  - type: web
    name: veripack
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000
